# This file contains all available configuration options
# with their default values.

# Options for analysis running
run:
  concurrency: 4
  timeout: 10m
  issues-exit-code: 1
  # Include test files or not, default is true
  tests: true
  skip-dirs:
    - "example"
    - "hack"

# Output configuration options
output:
  format: line-number

# All available settings of specific linters
linters-settings:
  misspell:
    locale: US
    ignore-words:
      - noteable

  goheader:
    template-path: .go-header.txt

linters:
  enable:
    - asciicheck
    - dogsled
    - errorlint
    - exportloopref
    - goconst
    - gosimple
    - govet
    - goheader
    - gomnd
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - unconvert
    - unused
    - whitespace
  disable-all: true
  fast: false

issues:
  exclude-rules:
    - linters:
        - goheader
      text: "Copyright"
