run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: checkstyle
      path: report.xml
    - format: colored-line-number


linters-settings:
  misspell:
    locale: US
    ignore-words:
      - noteable

  goheader:
    template-path: .go-header.txt

linters:
  enable:
    - asciicheck
    - dogsled
    - errorlint
    - goconst
    - gosimple
    - govet
    - goheader
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - unconvert
    - unused
    - whitespace
  disable-all: true
  fast: false

issues:
  exclude-dirs:
    - "example"
    - "hack"
  exclude-rules:
    - linters:
        - goheader
      text: "Copyright"
    - linters:
        - goheader
      text: "easysoft"
