# https://taskfile.dev

version: '3'

vars:
  GOPROXY: 'https://goproxy.cn,direct'
  GOSUMDB: sum.golang.google.cn

tasks:
  gencopyright:
    cmds:
      - go install github.com/google/addlicense@latest
      - ./gencopyright.sh

  gomod:
    desc: update go mod
    cmds:
      - go mod tidy

  gofmt:
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest
      - gofmt -s -w .
      - goimports -w .

  golint:
    desc: lint package
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - golangci-lint run -v ./...

  coverage:
    desc: test package
    cmds:
      - go test -v ./... -coverprofile=coverage.txt -covermode count
      - go tool cover -func=coverage.txt

  lint:
    desc: lint package
    cmds:
      - task: gofmt
      - task: golint

  fmt:
    cmds:
      - task: gomod
      - task: gencopyright
      - task: gofmt
      - task: golint

  default:
    cmds:
      - task: fmt
