# https://taskfile.dev

version: "3"

vars:
  GOPROXY: "https://goproxy.cn,direct"
  GOSUMDB: sum.golang.google.cn

tasks:
  gencopyright:
    cmds:
      - go install github.com/google/addlicense@latest
      - ./gencopyright.sh

  gomod:
    desc: update go mod
    cmds:
      - go mod tidy

  gofmt:
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest
      - gofmt -s -w .
      - goimports -w .

  golint:
    desc: lint package
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - golangci-lint run -v ./...

  coverage:
    desc: test package
    cmds:
      - go test -v ./... -coverprofile=coverage.txt -covermode count
      - go tool cover -func=coverage.txt

  gci:
    cmds:
      - go install github.com/daixiang0/gci@latest
      - gci write --skip-generated --custom-order -s standard -s "prefix(github.com/easysoft/go-zentao)" -s default -s blank -s dot .

  lint:
    desc: lint package
    cmds:
      - task: gomod
      - task: gofmt
      - task: golint
      - task: gci

  initgithooks:
    desc: pre dev init githooks
    run: once
    cmds:
      - git config core.hooksPath .githooks

  dev:
    desc: dev
    cmds:
      - docker compose -f hack/docker-compose.yml up -d

  clean:
    desc: clean
    cmds:
      - docker compose -f hack/docker-compose.yml down -v

  fmt:
    cmds:
      - task: initgithooks
      - task: gomod
      - task: gencopyright
      - task: gofmt
      - task: golint

  default:
    cmds:
      - task: initgithooks
      - task: fmt
