version: '2'

networks:
  zentao-net:
    driver: bridge

services:

# mysql service for zentao
  zentao-mysql:
    image: mysql:5.7
    container_name: zentao-mysql
    ports:
      - '3306:3306'
    volumes:
      - 'zentao_db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=pass4Zentao
      - MYSQL_DATABASE=zentao
    networks:
      - zentao-net

# zentao service
  zentao:
    image: hub.qucheng.com/app/quickon-zentao:${TAG:-latest}
    container_name: zentao
    ports:
      - '80:80'
    volumes:
      - 'zentao_data:/data'
    depends_on:
      - zentao-mysql
    environment:
      - MYSQL_HOST=zentao-mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass4Zentao
      - MYSQL_DB=zentao
      - EASYSOFT_DEBUG=true
      - DEBUG=1
      - IS_CONTAINER=true
    networks:
      - zentao-net

# persistence for mysql and zentao
volumes:
  zentao_db:
  zentao_data:
