basePath: /api.php/v1
host: zentao.demo.qucheng.cc
info:
  contact: {}
  description: This is a Go SDK for Zentao API.
  title: Zentao Go SDK
  version: v20.0
paths: {}
schemes:
- https
swagger: "2.0"
