name: check

env:
  # Common versions
  GO_VERSION: '1.23'
  TZ: Asia/Shanghai

permissions: write-all

on:
  pull_request:
    branches:
      - '*'
    paths:
      - '**.go'
      - 'go.mod'
      - '.github/workflows/**.yml'
  push:
    branches:
      - '*'
    paths:
      - '**.go'
      - 'go.mod'
      - '.github/workflows/**.yml'

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version: ${{ env.GO_VERSION }}
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Run Check License
        run: |
          task gencopyright
          modifyCode=$(git status  -s | grep M | wc -l)
          git status  -s
          if [ $modifyCode -eq 0 ] ; then
             echo "Lic check ok"
          else
             echo "Failed git modify files num is $modifyCode. Lic check error,please exec 'task gencopyright' in your code "
             exit -1
          fi
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Run Linter
        run: |
          task lint
          modifyCode=$(git status  -s | grep M | wc -l)
          git status  -s
          if [ $modifyCode -eq 0 ] ; then
              echo "Lic check ok"
          else
              echo "Failed git modify files num is $modifyCode. Lic check error,please exec 'task gencopyright' in your code "
              exit -1
          fi

  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - name: Lint package
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --issues-exit-code=1

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Test package
        run: |
          task coverage
      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0.3.0
        with:
          report: 'true'
          amend: 'true'
          reuse-go: 'true'
        continue-on-error: true
        if: github.event_name == 'push'
